name = "Han"
license = "MIT"
licenselink = "https://github.com/hanwentao/hugo-han/blob/master/LICENSE"
description = "A simple Hugo theme from Wentao Han"
homepage = "https://hanwentao.net/theme/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Wentao Han"
  homepage = "https://hanwentao.net"
